name: SSH CMD Action
description: Action to run an single ssh command
inputs:
  user:
    description: SSH user
    required: true
  host:
    description: Target host
    required: true
  port:
    description: Target port
    default: 22
  hostkey:
    description: Public key of the host server
    required: true
  userkey:
    description: Private key of the user
    required: true
  command:
    description: The command to execute
    required: true
runs:
  using: 'docker'
  image: docker://ghcr.io/anttihuokko/ssh-cmd-action:latest
  args:
    - --user=${{ inputs.user }}
    - --host=${{ inputs.host }}
    - --port=${{ inputs.port }}
    - --hostkey=${{ inputs.hostkey }}
    - --userkey=${{ inputs.userkey }}
    - --command=${{ inputs.command }}
