name: Docker Image CI
on:
  workflow_dispatch:
env:
  IMAGE_TAG: ghcr.io/${{ github.repository }}:latest
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --tag $IMAGE_TAG .
      - name: Push Docker image to repository
        run: docker push $IMAGE_TAG
