name: Image Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker image
        uses: docker://ghcr.io/anttihuokko/ssh-action:latest
        with:
          args: Hello Docker
